<a href="https://colab.research.google.com/github/CloakingGhost/BitPy/blob/main/221006.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://numpy.org/doc/stable/user/whatisnumpy.html

In [ ]:
#numpy 모듈을 사용하기 위한 import문
import numpy as np

In [ ]:
ls = [1,2,3,4,5]
arr = np.array(ls)
print(arr)
print(type(arr))# 다차원 배열을 포현하는 타입이 ndarray

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
ls1 = [1,2,3]
ls2 = [4,7,2]
ls3 = ls1+ls2
print(ls3) # 파이썬 리스트의 합은 concat

[1, 2, 3, 4, 7, 2]


In [ ]:
arr1 =np.array(ls1)
arr2=np.array(ls2)
arr3=arr1+arr2
print(arr3)#numpy의 +연산은 행렬의 +연산을 수행

In [ ]:
ls=1,2,3,
ls2= ls*3
print(ls2)

In [ ]:
arr = np.array[ls]
arr2 = arr*3
print(arr2)#numpy의 ndarray*(정수)는 (행렬)*(정수) 연산을 수행

모든 요소에 똑같은 연산을 수행하는 것이 브로드캐스팅
데이터를 분석을토대로 뭘해야하는지까지 상관계수를 찾는것은 필수적이다 A와B의 관계를 찾아야한다


###평균
실제값과 오차가 최소가 되는값 = 참값 = 대표값

###분위값
전체적 데이터 중 이상값은 버리고 통계를 낼것인지 말것인지 확인

###표준편차, 분산

---
- %%time을 마킹하면 수행시간을 측청해줍니다

In [ ]:
%%time 
arr = np.arange(100000)

CPU times: user 326 µs, sys: 0 ns, total: 326 µs
Wall time: 336 µs


In [ ]:
%%time
arr = list(range(100000))

CPU times: user 4.19 ms, sys: 3.13 ms, total: 7.32 ms
Wall time: 8.95 ms


In [ ]:
arr = np.random.randn(2,3) # 2X3 행렬을 생성(원소를 랜덤하게 생성)
print(arr)

[[ 0.27618783 -0.94065543  0.08353071]
 [-0.22843883  0.46761716  0.99121652]]


In [ ]:
# 연산의 결과가 반환된것이고 변수 자체가 바뀐것이 아니다
arr2 = arr*3
arr2

array([[ 0.82856349, -2.82196628,  0.25059214],
       [-0.6853165 ,  1.40285148,  2.97364957]])

In [ ]:
arr.shape #구조 확인

(2, 3)

In [ ]:
arr.ndim #차원 확인

2

In [ ]:
arr.dtype#원소타입확인

dtype('float64')

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3.2]) # 정수와 실수로 배열 생성 +> 모든 정수는 실수로 변환
print(arr1)
print(arr1.dtype)
print(type(arr1[0]))

print(arr2)
print(arr2.dtype) 
print(type(arr2[0])) #numpy 배열에 있는 원소들은 같은형식으로 되어있다

arr3 = np.array([1,2,3.2,'a'])
print(arr3)
print(arr3.dtype) 
print(type(arr3[0]))

[1 2 3]
int64
<class 'numpy.int64'>
[1.  2.  3.2]
float64
<class 'numpy.float64'>
['1' '2' '3.2' 'a']
<U32
<class 'numpy.str_'>


#다차원 배열 생성

In [ ]:
ls = [1,2,3]
arr = np.array(ls)#리스트를 입력 인자로 ndarray 개체 생성
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
arr=np.zeros(10)
print(arr)
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
print("원소(요소) 형식 : ",arr.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
구조 :  (10,)
차원 :  1
원소(요소) 형식 :  float64


In [ ]:
arr=np.zeros((3,6))
print(arr)
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
print("원소(요소) 형식 : ",arr.dtype)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
구조 :  (3, 6)
차원 :  2
원소(요소) 형식 :  float64


In [ ]:
arr=np.ones((3,6))
print(arr)
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
print("원소(요소) 형식 : ",arr.dtype)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
구조 :  (3, 6)
차원 :  2
원소(요소) 형식 :  float64


In [ ]:
arr=np.arange(20)
print(arr)
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
print("원소(요소) 형식 : ",arr.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
구조 :  (20,)
차원 :  1
원소(요소) 형식 :  int64


In [ ]:
arr=np.arange(3,20,4)
print(arr)
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
print("원소(요소) 형식 : ",arr.dtype)

[ 3  7 11 15 19]
구조 :  (5,)
차원 :  1
원소(요소) 형식 :  int64


---
#원소 타입


In [ ]:
arr=np.array([1,2,3])
print(type(arr[0]),type(arr[1]),type(arr[2]))
print(arr.dtype)
print(arr)

<class 'numpy.int64'> <class 'numpy.int64'> <class 'numpy.int64'>
int64
[1 2 3]


In [ ]:
arr=np.array([1,2,4.2],dtype=np.int32) #dtype 인자를 이용하여 명시적으로 원소 형식 결정
print(type(arr[0]),type(arr[1]),type(arr[2]))
print(arr.dtype)
print(arr)

<class 'numpy.int32'> <class 'numpy.int32'> <class 'numpy.int32'>
int32
[1 2 4]


---
#산술 연산

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("====")
arr2=arr*arr
print(arr2)

[[1 2 3]
 [4 5 6]]
====
[[ 1  4  9]
 [16 25 36]]


In [ ]:
arr2=arr-arr
print(arr2)

[[0 0 0]
 [0 0 0]]


In [ ]:
arr2=1/arr
print(arr2)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [ ]:
arr2=arr**0.5
print(arr2)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


#색인 및 슬라이싱

In [ ]:
arr = np.arange(1000)

In [ ]:
print(arr[5:8])

[5 6 7]


In [ ]:
# 처음부터 인덱스 미만까지
print(arr[:8])

[0 1 2 3 4 5 6 7]


In [ ]:
print(arr[995:])

[995 996 997 998 999]


In [ ]:
print(arr[-5:])

[995 996 997 998 999]


In [ ]:
arr = np.zeros(30)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


In [ ]:
# 일부 숫자를 갱신할수 있다
arr[5:8] = 7
print(arr)

[0. 0. 0. 0. 0. 7. 7. 7. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(arr[0])
print(arr[1])
print(arr[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
print(arr[0][2])

3


In [ ]:
#다차원 배열의 인덱스를 numpy에서 사용하는 방법
print(arr[0,2])

3


###소스 배열을 가지고 간단한 실험을 하기 위해서 복사하여 사용하기
원본의 내용을 오염시키지 않아야 할 때
흔한일은 아니다

In [ ]:
cp_arr = arr.copy()
print(cp_arr)
cp_arr = cp_arr*2
print(cp_arr)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
cp_arr = arr.copy() #arr과 cp_arr은 다른 객체를 참조 copy()메소드의 존재 이유
print(cp_arr)
cp_arr[0,1] = 8
print(cp_arr)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 8 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
cp_arr = arr #arr과 cp_arr은 같은 객체를 참조
print(cp_arr)
cp_arr[0,1] = 8
print(cp_arr)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 8 3]
 [4 5 6]
 [7 8 9]]
[[1 8 3]
 [4 5 6]
 [7 8 9]]


[[1 8 3]
 [4 5 6]
 [7 8 9]]
[[ 2 16  6]
 [ 8 10 12]
 [14 16 18]]
[[1 8 3]
 [4 5 6]
 [7 8 9]]


#filter
판다스에서 더욱 강력하게 느껴질 것이다

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,0,2])
filter = arr1>arr2
print(filter)
# 각 요소끼리 비교하여 Ture False를 반환한다

[False  True  True]


In [ ]:
arr = np.array([1,2,3])

filter = arr>=2
print(filter)

[False  True  True]


In [ ]:
res = arr[filter]
print(res)

[2 3]


In [ ]:
res = arr[~filter] # ~ 가 붙으면 반대(not)
print(res)

[1]


배운것을 확인하고 싶다면 작은 프로그램을 짜봐라
라이브러리를 배울때 하루에 100가지를 나가는데 어떻게 다 기억하겠는가

숙련을 위해 어떤프로그램이 적합할까?

#구조 변경 p155

In [ ]:
arr = np.arange(96)
print("구조: ",arr.shape)
print("차원: ",arr.ndim)

In [ ]:
arr2 = arr.reshape((6,16))
print("구조: ",arr2.shape)
print("차원: ",arr2.ndim)

In [ ]:
# arr2 = arr.reshape((7,13)) # 요소의 수가 정확히 떨어져야한다
# print("구조: ",arr2.shape)
# print("차원: ",arr2.ndim)

In [ ]:
arr2 = arr.reshape((6,-1)) # 구조 변경 요청할 때 하나의 차원은 -1로 표현가능 (알아서 계산)
print("구조: ",arr2.shape)
print("차원: ",arr2.ndim)

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr2 = arr.T # 각 열로 새로운 행렬을 만든다
print(arr)
print("====")
print(arr2)

In [ ]:
arr2 = arr.transpose() #arr.T와 arr.transpose() 같은결과(전치행렬)를 반환한다
print(arr)
print("=====")
print(arr2)

In [ ]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr2 = np.sqrt(arr) #원본이 바뀌는것이 아니다 ## arr**arr0.5와 같은 결과
print(arr2)
print(arr)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr1 = np.random.randn(2,3)
print(arr1)
print("====")
arr2 = np.random.randn(2,3)
print(arr2)

[[ 0.24058222  0.46882828 -1.04280659]
 [-0.32557287 -0.35544653  0.02379071]]
====
[[ 0.31096766 -1.48016884  0.06827727]
 [ 1.74369772 -2.2302653   0.51898936]]


In [ ]:
arr3 = np.maximum(arr1,arr2) # 큰 것만 가져온다
print(arr3)

[[ 0.31096766  0.46882828  0.06827727]
 [ 1.74369772 -0.35544653  0.51898936]]


In [ ]:
arr = np.random.randn(7)*5
arr

array([-7.57748256, -0.84496087, -4.86350132, -0.74965299,  2.92131827,
       -2.608587  ,  5.98453569])

In [ ]:
remainder, whole_part = np.modf(arr)
remainder

array([-0.57748256, -0.84496087, -0.86350132, -0.74965299,  0.92131827,
       -0.608587  ,  0.98453569])

#Numpy 안으로

In [ ]:
#잠시 파이썬 기본 문법 - 리스트 컴프리헨션
xs = [x*x+2+x+3 for x in range(1,10)] # 리스트 컴프리헨션
print(xs)

[7, 11, 17, 25, 35, 47, 61, 77, 95]


In [ ]:
#위에 문법을 풀어서 보자
xs = []
for x in range(1,10):
  xs.append(x*x+2*x+3)
print(xs)

[6, 11, 18, 27, 38, 51, 66, 83, 102]


---

In [ ]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])

In [ ]:
#잠시 파이썬 기본 문법 - zip 사용 예
ls1=[1,2,3]
ls2=['가','나','다']
for e1, e2 in zip(ls1, ls2):
  print(e1,e2)

1 가
2 나
3 다


p164

In [ ]:
result = [(x if c else y) for x,y,c in zip(xarr,yarr,cond)]
print(result)

[1.1, 2.2, 1.3, 1.4, 2.5]


In [ ]:
#위에 문법을 풀어서 보자
result=[]
for x,y,c in zip(xarr,yarr,cond):
  if c:
    result.append(x)
  else:
    result.append(y)
    print(result)

[1.1, 2.2]
[1.1, 2.2, 1.3, 1.4, 2.5]


In [ ]:
result1 = np.where(cond,xarr,yarr) # 조건, 배열 참일때 사용할 ,거짓일때 하용하는 
print(result1)

[1.1 2.2 1.3 1.4 2.5]


In [ ]:
result1 = np.where(cond,1,2)
print(result1)

[1 2 1 1 2]


In [ ]:
heights = np.random.normal(172.4,5,1000)# 평균 172.4 표준편차 5인 표본 1000개를 생성
print(heights)

In [ ]:
print("평균 : ",heights.mean()) # print("평균: ",np.mean(heights))
print("평균 : ",heights.sum()) # print("평균: ",np.sum(heights))

평균 :  172.43941699910357
평균 :  172439.41699910356


In [ ]:
h2 = heights.reshape(20,-1)# 평균 172.4 표준편차 5인 표본 1000개를 생성
print("구조 : ", h2.shape)
print(h2)

구조 :  (20, 50)


In [ ]:
print("평균(축1): ",h2.mean(axis=1)) # 로우 별 평균 axis
print("평균(축0): ",h2.mean(axis=0)) # 컬럼 별 평균

평균(축1):  [173.19669028 172.35706823 171.96304525 172.34906986 172.95662307
 172.45282554 172.29314082 173.29608046 172.31281202 172.11600057
 172.54023159 173.1889776  172.41976985 172.34033025 172.72523458
 171.55548879 172.61241659 172.41106023 172.38922126 171.31225313]
평균(축0):  [172.13712834 173.30462021 171.2682956  173.64767926 173.93579784
 173.31774832 171.83432947 171.14156149 171.25619429 170.97219058
 173.20159437 172.28512287 173.22697083 172.98420874 172.48685955
 171.63807932 171.05575753 170.41287526 173.00559088 173.30763731
 171.95901159 173.01659397 170.81734413 171.33869101 172.90784311
 171.88451636 173.55418282 172.67806245 172.1459527  169.71001538
 172.49388532 170.66909597 172.24279867 171.87886452 172.00321336
 174.43394649 173.59465569 172.45388072 173.29907407 173.18767654
 171.57186718 170.9047217  173.74535565 172.8028096  172.18856665
 174.58150146 173.9103692  171.86982725 175.01045333 172.69583104]


In [ ]:
print("합계(축0) :",h2.sum(axis=0))
print("합계(축1) :",h2.sum(axis=1))

합계(축0) : [3442.74256674 3466.09240412 3425.36591204 3472.95358511 3478.71595687
 3466.35496634 3436.68658938 3422.83122986 3425.12388582 3419.44381167
 3464.03188741 3445.70245739 3464.53941657 3459.68417479 3449.73719107
 3432.76158641 3421.11515066 3408.25750517 3460.11181751 3466.15274615
 3439.18023181 3460.33187932 3416.3468825  3426.77382021 3458.15686213
 3437.69032726 3471.08365631 3453.5612489  3442.91905401 3394.20030762
 3449.87770638 3413.38191937 3444.85597335 3437.57729034 3440.06426728
 3488.67892973 3471.89311375 3449.07761431 3465.98148143 3463.75353083
 3431.43734356 3418.09443393 3474.90711306 3456.05619191 3443.77133295
 3491.63002923 3478.20738408 3437.39654504 3500.20906655 3453.91662087]
합계(축1) : [8659.8345142  8617.85341164 8598.15226244 8617.45349286 8647.83115333
 8622.64127698 8614.657041   8664.80402315 8615.64060075 8605.80002844
 8627.01157932 8659.4488802  8620.98849269 8617.0165126  8636.26172915
 8577.77443956 8630.62082967 8620.55301155 8619.46106312 8

In [ ]:
print("분산: ",h2.var())
print("표준편차: ",h2.std())

분산:  24.927403411121002
표준편차:  4.992735063181402


In [ ]:
print("최솟값: ",h2.min())
print("최댓값: ",h2.max())

최솟값:  158.03767383535896
최댓값:  193.69632690950357


In [ ]:
print("최솟값이 있는 위치: ",heights.argmin())
print("최댓값이 있는 위치: ",heights.argmax())
print(heights[heights.argmin()],heights[heights.argmax()])

최솟값이 있는 위치:  97
최댓값이 있는 위치:  854
158.03767383535896 193.69632690950357


In [ ]:
#적분과 비슷
arr=np.array([1,2,4,2,7])
print("누적 함계:",arr.cumsum())
print("누적 곱:",arr.cumprod())

누적 함계: [ 1  3  7  9 16]


In [ ]:
arr.sort()
arr

array([1, 2, 2, 4, 7])

In [ ]:
ua = np.unique(arr)
ua

array([1, 2, 4, 7])

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
y=np.array([[2,3],[1,2],[4,5]])
re = x.dot(y)
print(x)
print("=====")
print(y)
print("=====")
print(re)

[[1 2 3]
 [4 5 6]]
=====
[[2 3]
 [1 2]
 [4 5]]
=====
[[16 22]
 [37 52]]


In [ ]:
for _ in range(10):
  print(np.random.uniform(-2,3)) # -2~3 사이의 랜덤한 실수를 반환

1.0643294982062401
0.184856956820453
-0.3138317140823119
-1.3719077379777438
0.7032158210986839
1.3272851024950088
2.643874800261753
0.5351990639586508
-1.9612522608966003
-0.8290780134417124


In [ ]:
for _ in range(10):
  print(np.random.randint(1,5),end=" ") #1에서 5사이의 랜덤한 정수 반환
print()

3 1 4 3 4 3 4 3 2 4 


왼쪽 길에 페로몬 20
오른쪽길에 페로몬 10
randint(0,30)<20

In [ ]:
volan = [1,7,2,8,9]
for _ in range(20):
  print(np.random.choice(volan),end=" ")
print()

1 9 9 7 8 1 7 1 8 1 2 8 2 8 9 8 2 8 8 9 


랜덤을 사용해도 시드(seed)가 남아있어서
시드를 정해주는데 주로 시간으로 시드를 정해준다

In [ ]:
np.random.seed(100)